Integrate Hitesh's improvements (predicate coreference) with the automatic pipeline
vered1986/OKR pull request #40
Opened 2017-09-26 13:40 UTC by shanybar

I added Hitesh's changes to the script coreference.py.
The main change is in the score function, that now use argument coreference information and lexical similarity between the lemmatized dependency heads in order to determine the score (instead of just comparing the head lemmas).

2017-09-26 18:30 UTC, kleinay requested changes
Hi,
Look at my comment and fix the small changes you agree with :)
then commit and push again. after that ask Gabi if he want to review also.

Nice work!

2017-09-26 18:30 UTC, kleinay commented on src/baseline_automatic_pipeline_system/coreference.py
> +    Receives predicate mentions and entity clusters and perform predicate coreference resolution
I would add the basic algorithm to this documentation

2017-09-26 18:30 UTC, kleinay commented on src/baseline_automatic_pipeline_system/coreference.py
> +        clean_cluster = []
I think this is neater:
`clean_cluster = [mention_tuple[0] for mention_tuple in cluster]`

And also maybe changing the name "clean_cluster" to something more meaningful (say "ids_of_cluster" or "mentions_ids", since you are taking the mention_id of each mention in the cluster)

2017-09-26 18:30 UTC, kleinay commented on src/baseline_automatic_pipeline_system/coreference.py
> +def cluster_prop_mentions(mention_list, score, argument_clusters, lexical_wt, argument_match_ratio):
I don't like having two functions (in same file) with same meaning - cluster_prop_mentions and cluster_proposition_mentions. I suggest changing this name to "greedy_prop_clustring" or something like that.

2017-09-26 18:30 UTC, kleinay commented on src/baseline_automatic_pipeline_system/coreference.py
> +    argument_score = len([other for other in cluster if
add comment explaining the calculation here (what is the meaning of argument_score)

2017-09-26 18:30 UTC, kleinay commented on src/baseline_automatic_pipeline_system/coreference.py
> +        lexical_score = lexical_matches / (1.0 * len(cluster))
This means we divide the number-of-matches with the number of props in the cluster - but if the cluster is containing IMPLICITs, we would like to discount those from the division, don't we?

2017-09-26 18:30 UTC, kleinay commented on src/baseline_automatic_pipeline_system/coreference.py
> +    :param arg_match_ratio: criteria of argument overlap = no of aligned arguments / no of arguments(minimum of proposition1 and proposition2)
instead of "no of (aligned) arguments.." use "number of arguments" or "#arguments..."

2017-09-26 18:30 UTC, kleinay commented on src/baseline_automatic_pipeline_system/coreference.py
> +    matched_arguments = 0
`matched_arguments = 0.0`

Otherwise the division at the end would be between integers

2017-09-26 18:30 UTC, kleinay commented on src/baseline_automatic_pipeline_system/coreference.py
> +    prop_mention1_args = []
here too, i prefer list-comprehension style, but it a flavor issue (I think its usually more readable):

```
prop_mention1_args = [arg_data['sentence_id'] +'_' + arg_key 
                      for arg_key,arg_data in prop_mention1_info['Arguments'].iteritems()]
```

2017-09-26 18:30 UTC, kleinay commented on src/baseline_automatic_pipeline_system/coreference.py
> +        print 'problem here:'
don't print, use `logging.error` function of the logging package.

2017-09-27 16:54 UTC, shanybar commented
@kleinay I added the requested changes.
@gabrielStanovsky please check if more changes are needed.

2017-09-27 17:25 UTC, kleinay requested changes
only this tiny issue (I think its a mistake), thanks

2017-09-27 17:25 UTC, kleinay commented on src/baseline_automatic_pipeline_system/coreference.py
> +            implicit_mentions = 0.0
I think this is a mistake, you are zeroing it implicit_mentions counter each iteration...

2017-09-28 07:44 UTC, gabrielStanovsky approved these changes
Looks good to me. 
Thanks!

2017-09-28 08:25 UTC, shanybar commented
Thanks, merging.

2017-09-28 08:26 UTC, merged